sudo: false
language: python
python:
  - 3.8

before_install:
  - python -m pip install -U pip

install:
  - python -m pip install -r requirements.txt coveralls

before_script:
  - python manage.py migrate

script:
  - coverage run manage.py test -v 3

after_success:
  - coveralls