sudo: false
language: python
python:
  - 3.8

install:
  - pip install -r requirements.txt

before_script:
  - python client/manage.py migrate

script:
  - coverage run client/manage.py test product -v 3

after_success:
  - coveralls