# Generated by Django 3.1.2 on 2020-10-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Produto')),
                ('barcode', models.PositiveIntegerField(unique=True, verbose_name='Código de Barras')),
            ],
        ),
    ]
